language: node_js
cache:
  yarn: true
notifications:
  email: false
node_js:
  - "11"
env:
  global:
    - NODE_ENV=production
install:
  - yarn
script:
  - yarn build
  - find public -type f -print | sort
deploy:
  provider: firebase
  token:
    secure: riflQtKi0mihmix47ugLwBuAELO80tA+rrg2eodonmy9se2365m0hBrBMEH+pocfFKkgYVBiPFEFcmixobf/u5g2IEN34Pi97qGq0a6QumbHzgu2FObdU2b28KlUf6C0qDk1OXa61pONnajggqi6h3IOz2XgJPBRlpHMY/GwZunicpz4cm+YkHroQ+cStTPZVOSbFusBCF3WTAlSs6HnH8duArwwmFC/P4qMVJZuaBoD/wBIjFT8IuXJbBJju/zAb+srfR73K5Sk3jGn3bw+K6CYC1KezmLIA3pvA4ARSZi6T57uMEpnHRZekfiIUdnjIY15UNSZrcaUIIITzyZL9EW1DBAIvGgJKkQzhvksp4ESHp7sMni9ua41QDN6bpzMSkvUZTU9QWVmPh0vtuP5DKWa3XnaGSeiVnRPxSqktBiORBR2cQAYy/Z9EtzoqVfExtgOiDMORQ3y+TE7kiCRefss5YbR7gBA/mrFt0EdYs+7ZyiwpMTpkV85g+41Uf+DQMuOttXwXIlMReyk0gkmjiQmtGfmFDlh+Sy8hBOqb37/ryFbxJGkV9px7jRDcQJedbSRqcfidqWEb52udn2RdIBZKIHwSOvKy3GoqFUQQG9ivNT/G2JHH6q7JetC12tyNhzA4Ok6D6LMuRWE2gHcacrlG0oat8Fy/IZTSjt/QxQ=
  on:
    branch:
      - dev
      - development
      - master
  skip_cleanup: true
